### ISSUE TITLE
Reduce SYS_ADMIN root caps or document why they are needed

### ISSUE THREAD

**Issue by destijl** [NVIDIA/dcgm-exporter#165]
Hi Folks,

We have a customer that wants to use your software but their internal security team is concerned with the need to run it with the SYS_ADMIN root capability, and that's blocking their adoption. There's a ton of power in that bag of privilege and security folks are wary of it because it's often used as a shortcut that breaks the principle of least privilege. SYS_ADMIN is blocked in the [Kubernets pod security standard baseline policy](https://kubernetes.io/docs/concepts/security/pod-security-standards/) and so won't run on many clusters.

I did a quick pass through the docs and didn't see an explanation of why it's required, apologies if I missed it.

Can you take a look at the root capabilities you need and reduce them to a smaller set, or if you need the complete set of capabilities in sys_admin, add an explanation about why into the docs? And if you haven't already it would be worth doing the same with your RBAC privileges too, I'm not sure what they are. I tried to take a quick look at the daemonset but it's hard to read with the templating.

Thanks!

**Comment by nikkon-dev** [comment]
@destijl,

Hello, thank you for contacting us.

The privileges associated with the dcgm-exporter container are somewhat complex, but I'll do my best to explain the most important points.

The requirement for SYS_ADMIN privileges comes from DCGM, while the dcgm-exporter binary is simply a client. The specific use cases for how and where DCGM (nv-hostengine) and dcgm-exporter (binary) run and communicate can vary.

Firstly, there are two main reasons why DCGM requires root privileges (although there are more, only two are related to dcgm-exporter monitoring): a) DCP metrics (field ids ≥ 1001) require root privileges unless configured otherwise in the kernel parameters (see [https://developer.nvidia.com/nvidia-development-tools-solutions-err_nvgpuctrperm-permission-issue-performance-counters#SolnAdminTag](https://developer.nvidia.com/nvidia-development-tools-solutions-err_nvgpuctrperm-permission-issue-performance-counters#SolnAdminTag) for more information); b) on MIG-enabled systems (this is currently unavoidable).

Secondly, there are different ways in which dcgm-exporter communicates with DCGM: a) embedded - this is the default option when nv-hostengine runs inside the dcgm-exporter process and inherits all dcgm-exporter process privileges; b) DCGM runs on bare-metal, and dcgm-exporter connects to it via a TCP socket or Unix domain socket that is mounted inside the dcgm-exporter container; c) DCGM runs in its own dedicated docker container and exposes port 5555, which is used by dcgm-exporter.

Options b) and c) do not require the dcgm-exporter container to have SYS_ADMIN caps, but DCGM must run as root on bare-metal or have SYS_ADMIN caps for the container.
