### ISSUE TITLE
Support of gpu utilization and memory utilization per instance

### ISSUE THREAD

**Issue by YANSDU** [NVIDIA/dcgm-exporter#50]
I found that dcgm-exporter in flex mode cannot report gpu utilization DCGM_FI_DEV_GPU_UTIL and  and memory utilization DCGM_FI_DEV_MEM_COPY_UTIL for each MIG instance. Is this a problem with my setup or is it not supported by dcgm for now?

**Comment by YANSDU** [comment]
Also, I found that there are issues with DCGM_FI_DEV_SM_CLOCK as well as DCGM_FI_DEV_MEM_CLOCK metrics. When I divide the A100 into 7 instances and run the program on one instance, the number of metrics is the same for all instances, which is definitely not true. My dcgm-exporter version is 2.3.4-2.6.4.

**Comment by nikkon-dev** [comment]
@YANSDU,

The DCGM_FI_DEV_GPU_UTIL metric is not supported for MIG instances. It would be best if you used DCGM_FI_PROF_* set of metrics instead.
As for SM_CLOCK and MEM_CLOCK - if I understand you correctly, this is expected behavior - all MIG instances on a physical GPU will have the same SM and MEM clocks. It's impossible to control them individually.

**Comment by YANSDU** [comment]
> @YANSDU,
> 
> The DCGM_FI_DEV_GPU_UTIL metric is not supported for MIG instances. It would be best if you used DCGM_FI_PROF_* set of metrics instead. As for SM_CLOCK and MEM_CLOCK - if I understand you correctly, this is expected behavior - all MIG instances on a physical GPU will have the same SM and MEM clocks. It's impossible to control them individually.

Thank you for your answer. I have now specified a path to file containing DCGM fields to collect using the -f option and started collecting DCP metrics. But when I did this, I found that the system reported an error of "DCP metrics not enabled", I guess this is because my host is connected to one A100 and two 2080Ti, but DCP metrics cannot be obtained from the 2080Ti.

So I try to specify A100 with -gpus "device=0" when starting the container. At this time, the error "Error starting nv-hostengine: DCGM initialization error" occurred. May I ask what is causing this or is there any way I can collect data from the A100 alone?

**Comment by nikkon-dev** [comment]
@YANSDU,

You are right, the DCP metrics are not supported on 2080Ti.
Could you try to run the `dcgmi dmon -e 1001` on the machine and see if works? A debug log from the nv-hostengine would also help: `nv-hostengine -f logfile.log --log-level debug`.
Instead of Flex mode, you may specify `-d=i:0,1,2,3,4,` to target just MIG instances (the whole GPU metric will be unavailable in this mode). 
There may be initialization issues on machines with different GPU generations, especially if some of them are not DCP capable. We are fixing such issues and asking for more details to better detect the root cause.
Please, double-check that you either run the container with elevated privileges, or the nv-hostengine runs as root on the node. DCP metrics need either root privileges (CAP_SYS_ADMIN) or driver configuration `modprobe nvidia NVreg_RestrictProfilingToAdminUsers=0`

**Comment by Lzhang-hub** [comment]
@nikkon-dev 
Hi, I have got DCGM_FI_PROF_GR_ENGINE_ACTIVE metric through `dcgm-export` and got GRACT through run `dcgmi dmon -e 1001` ,but I find the value is different,  so DCGM_FI_PROF_GR_ENGINE_ACTIVE  is the same as GRACT ?
