### ISSUE TITLE
Export Kubernetes Labels with Pods

### ISSUE THREAD

**Issue by alex-g-tejada** [NVIDIA/dcgm-exporter#99]
Hey!

We're using the helm chart within our kubernetes cluster. We're able to collect exported pod/namespace but labels belonging to the pods are not being collected. Is there a way to collect these as well?

**Comment by nikkon-dev** [comment]
@alex-g-tejada,

Currently, dcgm-exporter does not provide a way to output all pod labels to Prometheus.
This is not hard to add, but printing out all labels would overwhelm the output.
There should be some way to specify which pod labels are needed.
This may be a reasonable feature request.

**Comment by syandroo** [comment]
@nikkon-dev is there any way to specify adding replicaset / deployment to the output too? or would that be in line with the pod annotations request

**Comment by nikkon-dev** [comment]
@syandroo,
That would be a bit different as the ReplicaSet or Deployment names are not labels. But what information would you want to see there? Just names of a replicaset/deployment?

**Comment by syandroo** [comment]
@nikkon-dev either the names of the replicaset or deployment are good, but being able to export pod labels would be sufficient, as we have them labeled anyway

**Comment by thekuffs** [comment]
Hi, you don't want to do this as part of the dcgm exporter. You should make sure that these pods are collected with a kubernetes service discovery style job in prometheus. (https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod) You can then use a labelmap to assign pod labels as labels in prometheus. There's a perfectly good example at https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus-kubernetes.yml#L288.

**Comment by jkremser** [comment]
@thekuffs I don't think this is doable using the syntax you've linked (Service Discovery mechanism + "relabeling foo"). It would work if the metrics were scraped from the workload's pods itself, but that's not the case, we scrape the `dcgm-exporter`. 

Imagine I would like to see also the svcName or deployment name so that it would be possible to aggregate together metrics that pertain to a single logical AI workload. 

Currently, the exposed metrics look like this:

```
DCGM_FI_DEV_GPU_UTIL{gpu="0",UUID="GPU-7321bb2c-953d-987c-ce73-f71263aad40f",pci_bus_id="00000000:00:03.0",device="nvidia0",modelName="NVIDIA L4",Hostname="demo-gpu-nodes-wvl57-dn8jf",DCGM_FI_DRIVER_VERSION="550.144.03",container="main",namespace="default",pod="llama-5f9889b97d-znf9w"} 42
```

so one can write a PromQL like this `sum(rate(DCGM_FI_DRIVER_VERSION{pod=~"foo-.*"))}` but this is far from perfect, because if there is a pod called `foo-bar-znf9w`, it will be also included. What this issue is about (i think) is to have a way to sum apples w/ apples for multiple replicas of a single logical workload. For instance our use-case would be to use this info for scaling decisions. This is easily doable in OpenTelemetry world + vLLM framework using the [resourcedetection](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/README.md) processor. But I didn't find a way here.

I can imagine some complicated PromQL join query of this `DCGM_FI_DEV_GPU_UTIL` metric w/ some metric coming from kube-state-metrics that has the info about what pod pertain to what service, but having a way to propagate the service name to the metrics itself would be super useful.
